list = ['jaber',786933,18,'islam']
list2 = ['azharul','islam',123]
print(list)
print(list[0])
print(list[3])
print(list[1:3])
print(list[2:])
print(list + list2)
print(len(list))
list.append("cmt")
print(list)
list.insert(2,"os")
print(list)
list.remove(18)
print(list)
list.pop()
print(list)
list.index('jaber')
print(list)
list.clear()
print(list)
